modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="more_ores_and_armour"
version="1.0.0"
displayName="More Ores and Armour"
credits="Created by CJDabomb"
displayURL="https://github.com/CJDaBomb/The-Ultimate-Utility-Pack"
logoFile="logo.png"
authors="CJDaBomb"
description='''
This mod adds new ores from the real world into minecrafr
'''

[[dependencies.more_ores_and_armour]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.more_ores_and_armour]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0]"
    ordering="NONE"
    side="BOTH"



